# Generated by Django 5.0.4 on 2024-04-05 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('data_updated', models.DateTimeField(auto_now=True)),
                ('cat_name', models.CharField(max_length=100, verbose_name='Kategoriya nomini kiriting')),
                ('cat_photo', models.ImageField(blank=True, default=None, null=True, upload_to='category/photo', verbose_name='Categoriya uchun foto 370x240 olchamda')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='place_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='Slider/photo')),
            ],
        ),
        migrations.CreateModel(
            name='TypePlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('data_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('data_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Mahsulot nomini kiriting')),
                ('description', models.TextField(max_length=1500, verbose_name='Mahsulotga batafsil tarif')),
                ('price', models.DecimalField(decimal_places=0, default='0', max_digits=10, verbose_name='Narxni belgilang')),
                ('photo', models.ImageField(upload_to='product/photo', verbose_name='Tovar fotosini kiriting')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='my_app.category', verbose_name='Kategoriyani tanlang')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.places', verbose_name='Restoranni tanlang')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='places',
            name='type_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.typeplaces', verbose_name='Ovqatlanish maskani turini tanlang'),
        ),
    ]
