# Generated by Django 5.0.4 on 2024-04-05 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('data_updated', models.DateTimeField(auto_now=True)),
                ('cat_name', models.CharField(max_length=100, verbose_name='Kategoriya nomini kiriting')),
                ('cat_photo', models.ImageField(blank=True, default=None, null=True, upload_to='category/photo', verbose_name='Categoriya uchun foto 370x240 olchamda')),
                ('subcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.category', verbose_name='Ovqatlanish maskani turini tanlang')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='my_app.subcategory', verbose_name='Kategoriyani tanlang'),
        ),
    ]
