# Generated by Django 5.0.4 on 2024-04-05 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_subcategory_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='cat_name',
            new_name='subcat_name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='cat_photo',
            new_name='subcat_photo',
        ),
    ]
