# Generated by Django 5.0.4 on 2024-04-05 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_rename_cat_name_subcategory_subcat_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='my_app.places', verbose_name='Restoranni tanlang'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='my_app.category', verbose_name='Ovqatlanish maskani turini tanlang'),
        ),
    ]
