# Generated by Django 5.0.4 on 2024-04-05 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_product_restaurant_alter_subcategory_subcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products1', to='my_app.places', verbose_name='Restoranni tanlang'),
        ),
    ]
