# Generated by Django 5.0.4 on 2024-04-05 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_product_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='type_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_places', to='my_app.typeplaces', verbose_name='Ovqatlanish maskani turini tanlang'),
        ),
    ]
